// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yolo_max_pool_top_yolo_max_pool_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.140500,HLS_SYN_LAT=2076688,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=0,HLS_SYN_FF=1449,HLS_SYN_LUT=2530,HLS_VERSION=2022_2}" *)

module yolo_max_pool_top (
        ap_clk,
        ap_rst_n,
        inStream_TDATA,
        inStream_TVALID,
        inStream_TREADY,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TREADY,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [111:0] inStream_TDATA;
input   inStream_TVALID;
output   inStream_TREADY;
output  [111:0] outStream_TDATA;
output   outStream_TVALID;
input   outStream_TREADY;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [8:0] output_h;
wire   [8:0] output_w;
wire   [8:0] input_h;
wire   [8:0] input_w;
wire   [3:0] input_fold_ch;
wire   [1:0] stride;
reg   [1:0] stride_read_reg_727;
reg   [3:0] input_fold_ch_read_reg_735;
reg   [8:0] input_w_read_reg_743;
reg   [8:0] input_h_read_reg_749;
reg   [8:0] output_w_read_reg_754;
reg   [8:0] output_h_read_reg_760;
wire   [5:0] mul_ln4_fu_608_p2;
reg   [5:0] mul_ln4_reg_766;
wire    ap_CS_fsm_state2;
wire   [14:0] mul_ln4_1_fu_621_p2;
reg   [14:0] mul_ln4_1_reg_772;
wire   [16:0] mul_ln4_2_fu_633_p2;
reg   [16:0] mul_ln4_2_reg_779;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire  signed [25:0] grp_fu_721_p2;
reg   [25:0] mul_ln4_3_reg_795;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln1027_1_fu_645_p2;
reg   [0:0] icmp_ln1027_1_reg_800;
wire   [0:0] icmp_ln1027_2_fu_650_p2;
reg   [0:0] icmp_ln1027_2_reg_805;
wire   [2:0] sub_i_i270_fu_658_p2;
reg   [2:0] sub_i_i270_reg_810;
wire    ap_CS_fsm_state8;
wire   [9:0] sub_i_i87_fu_668_p2;
reg   [9:0] sub_i_i87_reg_815;
wire   [9:0] sub_i_i56_fu_678_p2;
reg   [9:0] sub_i_i56_reg_820;
wire   [4:0] sub_i_i_fu_688_p2;
reg   [4:0] sub_i_i_reg_825;
wire   [0:0] notlhs1_mid1182_fu_695_p2;
reg   [0:0] notlhs1_mid1182_reg_830;
wire   [0:0] notrhs_mid1192_fu_702_p2;
reg   [0:0] notrhs_mid1192_reg_835;
wire   [0:0] cmp_i_i606_not_mid1214_fu_709_p2;
reg   [0:0] cmp_i_i606_not_mid1214_reg_840;
wire   [0:0] icmp_ln1027_fu_715_p2;
reg   [0:0] icmp_ln1027_reg_845;
reg    line_buff_group_0_val_V_ce0;
wire   [15:0] line_buff_group_0_val_V_q0;
reg    line_buff_group_0_val_V_ce1;
reg    line_buff_group_0_val_V_we1;
reg    line_buff_group_0_val_V_1_ce0;
wire   [15:0] line_buff_group_0_val_V_1_q0;
reg    line_buff_group_0_val_V_1_ce1;
reg    line_buff_group_0_val_V_1_we1;
reg    line_buff_group_1_val_V_ce0;
wire   [15:0] line_buff_group_1_val_V_q0;
reg    line_buff_group_1_val_V_ce1;
reg    line_buff_group_1_val_V_we1;
reg    line_buff_group_1_val_V_1_ce0;
wire   [15:0] line_buff_group_1_val_V_1_q0;
reg    line_buff_group_1_val_V_1_ce1;
reg    line_buff_group_1_val_V_1_we1;
reg    line_buff_group_2_val_V_ce0;
wire   [15:0] line_buff_group_2_val_V_q0;
reg    line_buff_group_2_val_V_ce1;
reg    line_buff_group_2_val_V_we1;
reg    line_buff_group_2_val_V_1_ce0;
wire   [15:0] line_buff_group_2_val_V_1_q0;
reg    line_buff_group_2_val_V_1_ce1;
reg    line_buff_group_2_val_V_1_we1;
reg    line_buff_group_3_val_V_ce0;
wire   [15:0] line_buff_group_3_val_V_q0;
reg    line_buff_group_3_val_V_ce1;
reg    line_buff_group_3_val_V_we1;
reg    line_buff_group_3_val_V_1_ce0;
wire   [15:0] line_buff_group_3_val_V_1_q0;
reg    line_buff_group_3_val_V_1_ce1;
reg    line_buff_group_3_val_V_1_we1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_done;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_idle;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_ready;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_d1;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_address0;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_ce0;
wire   [11:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_address1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_ce1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_we1;
wire   [15:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_d1;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_inStream_TREADY;
wire   [111:0] grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TDATA;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TVALID;
wire    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TREADY;
reg    grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire   [1:0] mul_ln4_fu_608_p0;
wire   [3:0] mul_ln4_fu_608_p1;
wire   [8:0] mul_ln4_1_fu_621_p0;
wire   [5:0] mul_ln4_1_fu_621_p1;
wire   [1:0] mul_ln4_2_fu_633_p0;
wire   [14:0] mul_ln4_2_fu_633_p1;
wire   [2:0] stride_cast_fu_655_p1;
wire   [9:0] output_h_cast_fu_665_p1;
wire   [9:0] output_w_cast_fu_675_p1;
wire   [4:0] input_fold_ch_cast_fu_685_p1;
wire   [8:0] grp_fu_721_p0;
wire   [16:0] grp_fu_721_p1;
wire    regslice_both_outStream_U_apdone_blk;
reg   [9:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    regslice_both_inStream_U_apdone_blk;
wire   [111:0] inStream_TDATA_int_regslice;
wire    inStream_TVALID_int_regslice;
reg    inStream_TREADY_int_regslice;
wire    regslice_both_inStream_U_ack_in;
wire    outStream_TREADY_int_regslice;
wire    regslice_both_outStream_U_vld_out;
wire   [25:0] grp_fu_721_p00;
wire   [25:0] grp_fu_721_p10;
wire   [14:0] mul_ln4_1_fu_621_p00;
wire   [14:0] mul_ln4_1_fu_621_p10;
wire   [16:0] mul_ln4_2_fu_633_p00;
wire   [16:0] mul_ln4_2_fu_633_p10;
wire   [5:0] mul_ln4_fu_608_p00;
wire   [5:0] mul_ln4_fu_608_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start_reg = 1'b0;
end

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_0_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_address0),
    .ce0(line_buff_group_0_val_V_ce0),
    .q0(line_buff_group_0_val_V_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_address1),
    .ce1(line_buff_group_0_val_V_ce1),
    .we1(line_buff_group_0_val_V_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_0_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_address0),
    .ce0(line_buff_group_0_val_V_1_ce0),
    .q0(line_buff_group_0_val_V_1_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_address1),
    .ce1(line_buff_group_0_val_V_1_ce1),
    .we1(line_buff_group_0_val_V_1_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_1_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_address0),
    .ce0(line_buff_group_1_val_V_ce0),
    .q0(line_buff_group_1_val_V_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_address1),
    .ce1(line_buff_group_1_val_V_ce1),
    .we1(line_buff_group_1_val_V_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_1_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_address0),
    .ce0(line_buff_group_1_val_V_1_ce0),
    .q0(line_buff_group_1_val_V_1_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_address1),
    .ce1(line_buff_group_1_val_V_1_ce1),
    .we1(line_buff_group_1_val_V_1_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_2_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_address0),
    .ce0(line_buff_group_2_val_V_ce0),
    .q0(line_buff_group_2_val_V_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_address1),
    .ce1(line_buff_group_2_val_V_ce1),
    .we1(line_buff_group_2_val_V_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_2_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_address0),
    .ce0(line_buff_group_2_val_V_1_ce0),
    .q0(line_buff_group_2_val_V_1_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_address1),
    .ce1(line_buff_group_2_val_V_1_ce1),
    .we1(line_buff_group_2_val_V_1_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_3_val_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_address0),
    .ce0(line_buff_group_3_val_V_ce0),
    .q0(line_buff_group_3_val_V_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_address1),
    .ce1(line_buff_group_3_val_V_ce1),
    .we1(line_buff_group_3_val_V_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_d1)
);

yolo_max_pool_top_line_buff_group_0_val_V_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 3344 ),
    .AddressWidth( 12 ))
line_buff_group_3_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_address0),
    .ce0(line_buff_group_3_val_V_1_ce0),
    .q0(line_buff_group_3_val_V_1_q0),
    .address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_address1),
    .ce1(line_buff_group_3_val_V_1_ce1),
    .we1(line_buff_group_3_val_V_1_we1),
    .d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_d1)
);

yolo_max_pool_top_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start),
    .ap_done(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_done),
    .ap_idle(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_idle),
    .ap_ready(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_ready),
    .stride_cast6(stride_read_reg_727),
    .sub_i_i87(sub_i_i87_reg_815),
    .input_h_cast(input_h_read_reg_749),
    .sub_i_i270(sub_i_i270_reg_810),
    .sub_i_i56(sub_i_i56_reg_820),
    .input_w_cast(input_w_read_reg_743),
    .mul_ln4_3(mul_ln4_3_reg_795),
    .mul_ln4_2(mul_ln4_2_reg_779),
    .notlhs1_mid1182(notlhs1_mid1182_reg_830),
    .notrhs_mid1192(notrhs_mid1192_reg_835),
    .cmp_i_i606_not_mid1214(cmp_i_i606_not_mid1214_reg_840),
    .input_fold_ch(input_fold_ch_read_reg_735),
    .icmp_ln1027(icmp_ln1027_reg_845),
    .mul_ln4(mul_ln4_reg_766),
    .icmp_ln1027_1(icmp_ln1027_1_reg_800),
    .mul_ln4_1(mul_ln4_1_reg_772),
    .icmp_ln1027_2(icmp_ln1027_2_reg_805),
    .line_buff_group_0_val_V_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_address0),
    .line_buff_group_0_val_V_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_ce0),
    .line_buff_group_0_val_V_q0(line_buff_group_0_val_V_q0),
    .line_buff_group_0_val_V_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_address1),
    .line_buff_group_0_val_V_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_ce1),
    .line_buff_group_0_val_V_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_we1),
    .line_buff_group_0_val_V_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_d1),
    .line_buff_group_0_val_V_2_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_address0),
    .line_buff_group_0_val_V_2_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_ce0),
    .line_buff_group_0_val_V_2_q0(line_buff_group_0_val_V_1_q0),
    .line_buff_group_0_val_V_2_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_address1),
    .line_buff_group_0_val_V_2_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_ce1),
    .line_buff_group_0_val_V_2_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_we1),
    .line_buff_group_0_val_V_2_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_d1),
    .line_buff_group_1_val_V_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_address0),
    .line_buff_group_1_val_V_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_ce0),
    .line_buff_group_1_val_V_q0(line_buff_group_1_val_V_q0),
    .line_buff_group_1_val_V_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_address1),
    .line_buff_group_1_val_V_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_ce1),
    .line_buff_group_1_val_V_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_we1),
    .line_buff_group_1_val_V_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_d1),
    .line_buff_group_1_val_V_2_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_address0),
    .line_buff_group_1_val_V_2_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_ce0),
    .line_buff_group_1_val_V_2_q0(line_buff_group_1_val_V_1_q0),
    .line_buff_group_1_val_V_2_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_address1),
    .line_buff_group_1_val_V_2_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_ce1),
    .line_buff_group_1_val_V_2_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_we1),
    .line_buff_group_1_val_V_2_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_d1),
    .line_buff_group_2_val_V_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_address0),
    .line_buff_group_2_val_V_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_ce0),
    .line_buff_group_2_val_V_q0(line_buff_group_2_val_V_q0),
    .line_buff_group_2_val_V_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_address1),
    .line_buff_group_2_val_V_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_ce1),
    .line_buff_group_2_val_V_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_we1),
    .line_buff_group_2_val_V_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_d1),
    .line_buff_group_2_val_V_2_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_address0),
    .line_buff_group_2_val_V_2_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_ce0),
    .line_buff_group_2_val_V_2_q0(line_buff_group_2_val_V_1_q0),
    .line_buff_group_2_val_V_2_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_address1),
    .line_buff_group_2_val_V_2_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_ce1),
    .line_buff_group_2_val_V_2_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_we1),
    .line_buff_group_2_val_V_2_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_d1),
    .line_buff_group_3_val_V_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_address0),
    .line_buff_group_3_val_V_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_ce0),
    .line_buff_group_3_val_V_q0(line_buff_group_3_val_V_q0),
    .line_buff_group_3_val_V_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_address1),
    .line_buff_group_3_val_V_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_ce1),
    .line_buff_group_3_val_V_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_we1),
    .line_buff_group_3_val_V_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_d1),
    .line_buff_group_3_val_V_2_address0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_address0),
    .line_buff_group_3_val_V_2_ce0(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_ce0),
    .line_buff_group_3_val_V_2_q0(line_buff_group_3_val_V_1_q0),
    .line_buff_group_3_val_V_2_address1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_address1),
    .line_buff_group_3_val_V_2_ce1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_ce1),
    .line_buff_group_3_val_V_2_we1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_we1),
    .line_buff_group_3_val_V_2_d1(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_d1),
    .inStream_TDATA(inStream_TDATA_int_regslice),
    .inStream_TVALID(inStream_TVALID_int_regslice),
    .inStream_TREADY(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_inStream_TREADY),
    .sub_i_i(sub_i_i_reg_825),
    .outStream_TDATA(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TDATA),
    .outStream_TVALID(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TVALID),
    .outStream_TREADY(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TREADY)
);

yolo_max_pool_top_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .output_h(output_h),
    .output_w(output_w),
    .input_h(input_h),
    .input_w(input_w),
    .input_fold_ch(input_fold_ch),
    .stride(stride),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

yolo_max_pool_top_mul_2ns_4ns_6_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 6 ))
mul_2ns_4ns_6_1_1_U40(
    .din0(mul_ln4_fu_608_p0),
    .din1(mul_ln4_fu_608_p1),
    .dout(mul_ln4_fu_608_p2)
);

yolo_max_pool_top_mul_9ns_6ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 15 ))
mul_9ns_6ns_15_1_1_U41(
    .din0(mul_ln4_1_fu_621_p0),
    .din1(mul_ln4_1_fu_621_p1),
    .dout(mul_ln4_1_fu_621_p2)
);

yolo_max_pool_top_mul_2ns_15ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 17 ))
mul_2ns_15ns_17_1_1_U42(
    .din0(mul_ln4_2_fu_633_p0),
    .din1(mul_ln4_2_fu_633_p1),
    .dout(mul_ln4_2_fu_633_p2)
);

yolo_max_pool_top_mul_mul_9ns_17ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 26 ))
mul_mul_9ns_17ns_26_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_721_p0),
    .din1(grp_fu_721_p1),
    .ce(1'b1),
    .dout(grp_fu_721_p2)
);

yolo_max_pool_top_regslice_both #(
    .DataWidth( 112 ))
regslice_both_inStream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_TDATA),
    .vld_in(inStream_TVALID),
    .ack_in(regslice_both_inStream_U_ack_in),
    .data_out(inStream_TDATA_int_regslice),
    .vld_out(inStream_TVALID_int_regslice),
    .ack_out(inStream_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream_U_apdone_blk)
);

yolo_max_pool_top_regslice_both #(
    .DataWidth( 112 ))
regslice_both_outStream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TDATA),
    .vld_in(grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TVALID),
    .ack_in(outStream_TREADY_int_regslice),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start_reg <= 1'b1;
        end else if ((grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_ready == 1'b1)) begin
            grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cmp_i_i606_not_mid1214_reg_840 <= cmp_i_i606_not_mid1214_fu_709_p2;
        icmp_ln1027_reg_845 <= icmp_ln1027_fu_715_p2;
        notlhs1_mid1182_reg_830 <= notlhs1_mid1182_fu_695_p2;
        notrhs_mid1192_reg_835 <= notrhs_mid1192_fu_702_p2;
        sub_i_i270_reg_810 <= sub_i_i270_fu_658_p2;
        sub_i_i56_reg_820 <= sub_i_i56_fu_678_p2;
        sub_i_i87_reg_815 <= sub_i_i87_fu_668_p2;
        sub_i_i_reg_825 <= sub_i_i_fu_688_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        icmp_ln1027_1_reg_800 <= icmp_ln1027_1_fu_645_p2;
        icmp_ln1027_2_reg_805 <= icmp_ln1027_2_fu_650_p2;
        mul_ln4_3_reg_795 <= grp_fu_721_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_fold_ch_read_reg_735 <= input_fold_ch;
        input_h_read_reg_749 <= input_h;
        input_w_read_reg_743 <= input_w;
        output_h_read_reg_760 <= output_h;
        output_w_read_reg_754 <= output_w;
        stride_read_reg_727 <= stride;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        mul_ln4_1_reg_772 <= mul_ln4_1_fu_621_p2;
        mul_ln4_reg_766 <= mul_ln4_fu_608_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln4_2_reg_779 <= mul_ln4_2_fu_633_p2;
    end
end

always @ (*) begin
    if ((regslice_both_outStream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_outStream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_outStream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        inStream_TREADY_int_regslice = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_inStream_TREADY;
    end else begin
        inStream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_0_val_V_1_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_ce0;
    end else begin
        line_buff_group_0_val_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_0_val_V_1_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_ce1;
    end else begin
        line_buff_group_0_val_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_0_val_V_1_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_2_we1;
    end else begin
        line_buff_group_0_val_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_0_val_V_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_ce0;
    end else begin
        line_buff_group_0_val_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_0_val_V_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_ce1;
    end else begin
        line_buff_group_0_val_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_0_val_V_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_0_val_V_we1;
    end else begin
        line_buff_group_0_val_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_1_val_V_1_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_ce0;
    end else begin
        line_buff_group_1_val_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_1_val_V_1_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_ce1;
    end else begin
        line_buff_group_1_val_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_1_val_V_1_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_2_we1;
    end else begin
        line_buff_group_1_val_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_1_val_V_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_ce0;
    end else begin
        line_buff_group_1_val_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_1_val_V_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_ce1;
    end else begin
        line_buff_group_1_val_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_1_val_V_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_1_val_V_we1;
    end else begin
        line_buff_group_1_val_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_2_val_V_1_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_ce0;
    end else begin
        line_buff_group_2_val_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_2_val_V_1_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_ce1;
    end else begin
        line_buff_group_2_val_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_2_val_V_1_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_2_we1;
    end else begin
        line_buff_group_2_val_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_2_val_V_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_ce0;
    end else begin
        line_buff_group_2_val_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_2_val_V_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_ce1;
    end else begin
        line_buff_group_2_val_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_2_val_V_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_2_val_V_we1;
    end else begin
        line_buff_group_2_val_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_3_val_V_1_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_ce0;
    end else begin
        line_buff_group_3_val_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_3_val_V_1_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_ce1;
    end else begin
        line_buff_group_3_val_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_3_val_V_1_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_2_we1;
    end else begin
        line_buff_group_3_val_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_3_val_V_ce0 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_ce0;
    end else begin
        line_buff_group_3_val_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_3_val_V_ce1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_ce1;
    end else begin
        line_buff_group_3_val_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        line_buff_group_3_val_V_we1 = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_line_buff_group_3_val_V_we1;
    end else begin
        line_buff_group_3_val_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_outStream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i_i606_not_mid1214_fu_709_p2 = ((input_w_read_reg_743 == 9'd0) ? 1'b1 : 1'b0);

assign grp_fu_721_p0 = grp_fu_721_p00;

assign grp_fu_721_p00 = output_h_read_reg_760;

assign grp_fu_721_p1 = grp_fu_721_p10;

assign grp_fu_721_p10 = mul_ln4_2_reg_779;

assign grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start = grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_ap_start_reg;

assign grp_yolo_max_pool_top_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_33_3_VITIS_LOOP_36_4_VITIS_fu_568_outStream_TREADY = (outStream_TREADY_int_regslice & ap_CS_fsm_state9);

assign icmp_ln1027_1_fu_645_p2 = ((mul_ln4_reg_766 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_2_fu_650_p2 = ((mul_ln4_1_reg_772 == 15'd0) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_715_p2 = ((input_fold_ch_read_reg_735 == 4'd0) ? 1'b1 : 1'b0);

assign inStream_TREADY = regslice_both_inStream_U_ack_in;

assign input_fold_ch_cast_fu_685_p1 = input_fold_ch_read_reg_735;

assign mul_ln4_1_fu_621_p0 = mul_ln4_1_fu_621_p00;

assign mul_ln4_1_fu_621_p00 = output_w_read_reg_754;

assign mul_ln4_1_fu_621_p1 = mul_ln4_1_fu_621_p10;

assign mul_ln4_1_fu_621_p10 = mul_ln4_fu_608_p2;

assign mul_ln4_2_fu_633_p0 = mul_ln4_2_fu_633_p00;

assign mul_ln4_2_fu_633_p00 = stride_read_reg_727;

assign mul_ln4_2_fu_633_p1 = mul_ln4_2_fu_633_p10;

assign mul_ln4_2_fu_633_p10 = mul_ln4_1_reg_772;

assign mul_ln4_fu_608_p0 = mul_ln4_fu_608_p00;

assign mul_ln4_fu_608_p00 = stride_read_reg_727;

assign mul_ln4_fu_608_p1 = mul_ln4_fu_608_p10;

assign mul_ln4_fu_608_p10 = input_fold_ch_read_reg_735;

assign notlhs1_mid1182_fu_695_p2 = ((sub_i_i270_fu_658_p2 != 3'd0) ? 1'b1 : 1'b0);

assign notrhs_mid1192_fu_702_p2 = ((sub_i_i56_fu_678_p2 == 10'd0) ? 1'b1 : 1'b0);

assign outStream_TVALID = regslice_both_outStream_U_vld_out;

assign output_h_cast_fu_665_p1 = output_h_read_reg_760;

assign output_w_cast_fu_675_p1 = output_w_read_reg_754;

assign stride_cast_fu_655_p1 = stride_read_reg_727;

assign sub_i_i270_fu_658_p2 = ($signed(stride_cast_fu_655_p1) + $signed(3'd7));

assign sub_i_i56_fu_678_p2 = ($signed(output_w_cast_fu_675_p1) + $signed(10'd1023));

assign sub_i_i87_fu_668_p2 = ($signed(output_h_cast_fu_665_p1) + $signed(10'd1023));

assign sub_i_i_fu_688_p2 = ($signed(input_fold_ch_cast_fu_685_p1) + $signed(5'd31));


reg find_kernel_block = 0;
// synthesis translate_off
`include "yolo_max_pool_top_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //yolo_max_pool_top

