-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yolo_conv_top_window_macc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of yolo_conv_top_window_macc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal p_read_reg_286 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_read_2_reg_291 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_2_reg_291_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_3_reg_296 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_5_reg_301 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_8_reg_306 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_9_reg_311 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_11_reg_316 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_11_reg_316_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_12_reg_321 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read412_reg_326 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read19_reg_331 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_227_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_245_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_reg_446 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_reg_446_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_253_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_1_reg_451 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_1_reg_451_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_261_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_3_reg_456 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_269_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_6_fu_208_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln813_6_fu_208_p2 : signal is "no";
    signal add_ln813_6_reg_466 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_ln813_6_fu_208_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_277_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln813_2_fu_212_p2 : STD_LOGIC_VECTOR (31 downto 0);
    attribute use_dsp48 of add_ln813_2_fu_212_p2 : signal is "no";
    signal sum_V_fu_216_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_221_ce : STD_LOGIC;
    signal grp_fu_227_ce : STD_LOGIC;
    signal grp_fu_233_ce : STD_LOGIC;
    signal grp_fu_239_ce : STD_LOGIC;
    signal grp_fu_245_ce : STD_LOGIC;
    signal grp_fu_253_ce : STD_LOGIC;
    signal grp_fu_261_ce : STD_LOGIC;
    signal grp_fu_269_ce : STD_LOGIC;
    signal grp_fu_277_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal p_read1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read5_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read6_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read7_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read8_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read9_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read10_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read11_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read12_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read13_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read14_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read15_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read16_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read17_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read18_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);

    component yolo_conv_top_mul_mul_16s_16s_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component yolo_conv_top_mac_muladd_16s_16s_32s_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component yolo_conv_top_mac_muladd_16s_16s_32ns_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_mul_16s_16s_32_4_0_U100 : component yolo_conv_top_mul_mul_16s_16s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read11_int_reg,
        din1 => p_read2_int_reg,
        ce => grp_fu_221_ce,
        dout => grp_fu_221_p2);

    mul_mul_16s_16s_32_4_0_U101 : component yolo_conv_top_mul_mul_16s_16s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read12_int_reg,
        din1 => p_read3_int_reg,
        ce => grp_fu_227_ce,
        dout => grp_fu_227_p2);

    mul_mul_16s_16s_32_4_0_U102 : component yolo_conv_top_mul_mul_16s_16s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read14_int_reg,
        din1 => p_read5_int_reg,
        ce => grp_fu_233_ce,
        dout => grp_fu_233_p2);

    mul_mul_16s_16s_32_4_0_U103 : component yolo_conv_top_mul_mul_16s_16s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read17_int_reg,
        din1 => p_read8_int_reg,
        ce => grp_fu_239_ce,
        dout => grp_fu_239_p2);

    mac_muladd_16s_16s_32s_32_4_0_U104 : component yolo_conv_top_mac_muladd_16s_16s_32s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_8_reg_306,
        din1 => p_read19_reg_331,
        din2 => grp_fu_221_p2,
        ce => grp_fu_245_ce,
        dout => grp_fu_245_p3);

    mac_muladd_16s_16s_32s_32_4_0_U105 : component yolo_conv_top_mac_muladd_16s_16s_32s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_5_reg_301,
        din1 => p_read412_reg_326,
        din2 => grp_fu_227_p2,
        ce => grp_fu_253_ce,
        dout => grp_fu_253_p3);

    mac_muladd_16s_16s_32s_32_4_0_U106 : component yolo_conv_top_mac_muladd_16s_16s_32s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_3_reg_296,
        din1 => p_read_12_reg_321,
        din2 => grp_fu_233_p2,
        ce => grp_fu_261_ce,
        dout => grp_fu_261_p3);

    mac_muladd_16s_16s_32s_32_4_0_U107 : component yolo_conv_top_mac_muladd_16s_16s_32s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_reg_286,
        din1 => p_read_9_reg_311,
        din2 => grp_fu_239_p2,
        ce => grp_fu_269_ce,
        dout => grp_fu_269_p3);

    mac_muladd_16s_16s_32ns_32_4_0_U108 : component yolo_conv_top_mac_muladd_16s_16s_32ns_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_read_2_reg_291_pp0_iter1_reg,
        din1 => p_read_11_reg_316_pp0_iter1_reg,
        din2 => grp_fu_269_p3,
        ce => grp_fu_277_ce,
        dout => grp_fu_277_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                add_ln813_1_reg_451 <= grp_fu_253_p3;
                add_ln813_1_reg_451_pp0_iter5_reg <= add_ln813_1_reg_451;
                add_ln813_3_reg_456 <= grp_fu_261_p3;
                add_ln813_6_reg_466 <= add_ln813_6_fu_208_p2;
                add_ln813_reg_446 <= grp_fu_245_p3;
                add_ln813_reg_446_pp0_iter5_reg <= add_ln813_reg_446;
                p_read19_reg_331 <= p_read1_int_reg;
                p_read412_reg_326 <= p_read4_int_reg;
                p_read_11_reg_316 <= p_read7_int_reg;
                p_read_11_reg_316_pp0_iter1_reg <= p_read_11_reg_316;
                p_read_12_reg_321 <= p_read6_int_reg;
                p_read_2_reg_291 <= p_read16_int_reg;
                p_read_2_reg_291_pp0_iter1_reg <= p_read_2_reg_291;
                p_read_3_reg_296 <= p_read15_int_reg;
                p_read_5_reg_301 <= p_read13_int_reg;
                p_read_8_reg_306 <= p_read10_int_reg;
                p_read_9_reg_311 <= p_read9_int_reg;
                p_read_reg_286 <= p_read18_int_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= sum_V_fu_216_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                p_read10_int_reg <= p_read10;
                p_read11_int_reg <= p_read11;
                p_read12_int_reg <= p_read12;
                p_read13_int_reg <= p_read13;
                p_read14_int_reg <= p_read14;
                p_read15_int_reg <= p_read15;
                p_read16_int_reg <= p_read16;
                p_read17_int_reg <= p_read17;
                p_read18_int_reg <= p_read18;
                p_read1_int_reg <= p_read1;
                p_read2_int_reg <= p_read2;
                p_read3_int_reg <= p_read3;
                p_read4_int_reg <= p_read4;
                p_read5_int_reg <= p_read5;
                p_read6_int_reg <= p_read6;
                p_read7_int_reg <= p_read7;
                p_read8_int_reg <= p_read8;
                p_read9_int_reg <= p_read9;
            end if;
        end if;
    end process;
    add_ln813_2_fu_212_p2 <= std_logic_vector(signed(add_ln813_1_reg_451_pp0_iter5_reg) + signed(add_ln813_reg_446_pp0_iter5_reg));
    add_ln813_6_fu_208_p0 <= grp_fu_277_p3;
    add_ln813_6_fu_208_p2 <= std_logic_vector(signed(add_ln813_6_fu_208_p0) + signed(add_ln813_3_reg_456));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_assign_proc : process(sum_V_fu_216_p2, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= sum_V_fu_216_p2;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_221_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_221_ce <= ap_const_logic_1;
        else 
            grp_fu_221_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_227_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_227_ce <= ap_const_logic_1;
        else 
            grp_fu_227_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_233_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_233_ce <= ap_const_logic_1;
        else 
            grp_fu_233_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_239_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_239_ce <= ap_const_logic_1;
        else 
            grp_fu_239_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_245_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_245_ce <= ap_const_logic_1;
        else 
            grp_fu_245_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_253_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_253_ce <= ap_const_logic_1;
        else 
            grp_fu_253_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_261_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_261_ce <= ap_const_logic_1;
        else 
            grp_fu_261_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_269_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_269_ce <= ap_const_logic_1;
        else 
            grp_fu_269_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_277_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_277_ce <= ap_const_logic_1;
        else 
            grp_fu_277_ce <= ap_const_logic_0;
        end if; 
    end process;

    sum_V_fu_216_p2 <= std_logic_vector(unsigned(add_ln813_6_reg_466) + unsigned(add_ln813_2_fu_212_p2));
end behav;
