// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="yolo_acc_top_yolo_acc_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.648500,HLS_SYN_LAT=1384472,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1559,HLS_SYN_LUT=2108,HLS_VERSION=2022_2}" *)

module yolo_acc_top (
        ap_clk,
        ap_rst_n,
        inStream_a_TDATA,
        inStream_a_TVALID,
        inStream_a_TREADY,
        inStream_b_TDATA,
        inStream_b_TVALID,
        inStream_b_TREADY,
        outStream_TDATA,
        outStream_TVALID,
        outStream_TREADY,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [111:0] inStream_a_TDATA;
input   inStream_a_TVALID;
output   inStream_a_TREADY;
input  [111:0] inStream_b_TDATA;
input   inStream_b_TVALID;
output   inStream_b_TREADY;
output  [111:0] outStream_TDATA;
output   outStream_TVALID;
input   outStream_TREADY;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [8:0] input_h;
wire   [8:0] input_w;
wire   [3:0] fold_input_ch;
wire   [0:0] leaky;
wire   [0:0] bias_en;
reg   [0:0] bias_en_read_reg_194;
reg   [0:0] leaky_read_reg_200;
reg   [3:0] fold_input_ch_read_reg_205;
reg   [8:0] input_w_read_reg_213;
reg   [8:0] input_h_read_reg_219;
wire   [12:0] bound_fu_141_p2;
reg   [12:0] bound_reg_225;
wire    ap_CS_fsm_state2;
wire   [9:0] sub_i_i54_fu_157_p2;
reg   [9:0] sub_i_i54_reg_240;
wire    ap_CS_fsm_state5;
wire   [9:0] sub_i_i_fu_167_p2;
reg   [9:0] sub_i_i_reg_245;
wire  signed [21:0] grp_fu_187_p2;
reg   [21:0] bound4_reg_250;
wire   [0:0] cmp_i_i31_mid111_fu_174_p2;
reg   [0:0] cmp_i_i31_mid111_reg_255;
wire   [0:0] icmp_ln1027_fu_181_p2;
reg   [0:0] icmp_ln1027_reg_260;
reg   [4:0] kernel_bias_fp_V_address0;
reg    kernel_bias_fp_V_ce0;
reg    kernel_bias_fp_V_we0;
wire   [15:0] kernel_bias_fp_V_q0;
reg   [4:0] kernel_bias_fp_V_address1;
reg    kernel_bias_fp_V_ce1;
reg    kernel_bias_fp_V_we1;
wire   [15:0] kernel_bias_fp_V_q1;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_done;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_idle;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_ready;
wire   [4:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_address0;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_ce0;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_we0;
wire   [15:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_d0;
wire   [4:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_address1;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_ce1;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_we1;
wire   [15:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_d1;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_inStream_b_TREADY;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_done;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_idle;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_ready;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TREADY;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_inStream_a_TREADY;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_inStream_b_TREADY;
wire   [4:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_address0;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_ce0;
wire   [4:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_address1;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_ce1;
wire   [111:0] grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TDATA;
wire    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TVALID;
reg    grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [8:0] bound_fu_141_p0;
wire   [3:0] bound_fu_141_p1;
wire   [9:0] input_w_cast_fu_154_p1;
wire   [9:0] input_h_cast_fu_164_p1;
wire   [8:0] grp_fu_187_p0;
wire   [12:0] grp_fu_187_p1;
reg    grp_fu_187_ce;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state7;
wire    regslice_both_outStream_U_apdone_blk;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    regslice_both_inStream_a_U_apdone_blk;
wire   [111:0] inStream_a_TDATA_int_regslice;
wire    inStream_a_TVALID_int_regslice;
reg    inStream_a_TREADY_int_regslice;
wire    regslice_both_inStream_a_U_ack_in;
wire    regslice_both_inStream_b_U_apdone_blk;
wire   [111:0] inStream_b_TDATA_int_regslice;
wire    inStream_b_TVALID_int_regslice;
reg    inStream_b_TREADY_int_regslice;
wire    regslice_both_inStream_b_U_ack_in;
wire    outStream_TREADY_int_regslice;
wire    regslice_both_outStream_U_vld_out;
wire   [12:0] bound_fu_141_p00;
wire   [12:0] bound_fu_141_p10;
wire   [21:0] grp_fu_187_p00;
wire   [21:0] grp_fu_187_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start_reg = 1'b0;
#0 grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start_reg = 1'b0;
end

yolo_acc_top_kernel_bias_fp_V_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
kernel_bias_fp_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(kernel_bias_fp_V_address0),
    .ce0(kernel_bias_fp_V_ce0),
    .we0(kernel_bias_fp_V_we0),
    .d0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_d0),
    .q0(kernel_bias_fp_V_q0),
    .address1(kernel_bias_fp_V_address1),
    .ce1(kernel_bias_fp_V_ce1),
    .we1(kernel_bias_fp_V_we1),
    .d1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_d1),
    .q1(kernel_bias_fp_V_q1)
);

yolo_acc_top_yolo_acc_top_Pipeline_VITIS_LOOP_25_1 grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start),
    .ap_done(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_done),
    .ap_idle(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_idle),
    .ap_ready(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_ready),
    .inStream_b_TVALID(inStream_b_TVALID_int_regslice),
    .fold_input_ch(fold_input_ch_read_reg_205),
    .kernel_bias_fp_V_address0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_address0),
    .kernel_bias_fp_V_ce0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_ce0),
    .kernel_bias_fp_V_we0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_we0),
    .kernel_bias_fp_V_d0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_d0),
    .kernel_bias_fp_V_address1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_address1),
    .kernel_bias_fp_V_ce1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_ce1),
    .kernel_bias_fp_V_we1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_we1),
    .kernel_bias_fp_V_d1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_d1),
    .bias_en(bias_en_read_reg_194),
    .inStream_b_TDATA(inStream_b_TDATA_int_regslice),
    .inStream_b_TREADY(grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_inStream_b_TREADY)
);

yolo_acc_top_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4 grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start),
    .ap_done(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_done),
    .ap_idle(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_idle),
    .ap_ready(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_ready),
    .outStream_TREADY(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TREADY),
    .sub_i_i(sub_i_i_reg_245),
    .sub_i_i54(sub_i_i54_reg_240),
    .bound4(bound4_reg_250),
    .bound(bound_reg_225),
    .cmp_i_i31_mid111(cmp_i_i31_mid111_reg_255),
    .fold_input_ch(fold_input_ch_read_reg_205),
    .icmp_ln1027(icmp_ln1027_reg_260),
    .inStream_a_TDATA(inStream_a_TDATA_int_regslice),
    .inStream_a_TVALID(inStream_a_TVALID_int_regslice),
    .inStream_a_TREADY(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_inStream_a_TREADY),
    .inStream_b_TDATA(inStream_b_TDATA_int_regslice),
    .inStream_b_TVALID(inStream_b_TVALID_int_regslice),
    .inStream_b_TREADY(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_inStream_b_TREADY),
    .kernel_bias_fp_V_address0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_address0),
    .kernel_bias_fp_V_ce0(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_ce0),
    .kernel_bias_fp_V_q0(kernel_bias_fp_V_q0),
    .kernel_bias_fp_V_address1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_address1),
    .kernel_bias_fp_V_ce1(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_ce1),
    .kernel_bias_fp_V_q1(kernel_bias_fp_V_q1),
    .bias_en(bias_en_read_reg_194),
    .leaky(leaky_read_reg_200),
    .outStream_TDATA(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TDATA),
    .outStream_TVALID(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TVALID)
);

yolo_acc_top_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_h(input_h),
    .input_w(input_w),
    .fold_input_ch(fold_input_ch),
    .leaky(leaky),
    .bias_en(bias_en),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

yolo_acc_top_mul_9ns_4ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 4 ),
    .dout_WIDTH( 13 ))
mul_9ns_4ns_13_1_1_U24(
    .din0(bound_fu_141_p0),
    .din1(bound_fu_141_p1),
    .dout(bound_fu_141_p2)
);

yolo_acc_top_mul_mul_9ns_13ns_22_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 22 ))
mul_mul_9ns_13ns_22_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_187_p0),
    .din1(grp_fu_187_p1),
    .ce(grp_fu_187_ce),
    .dout(grp_fu_187_p2)
);

yolo_acc_top_regslice_both #(
    .DataWidth( 112 ))
regslice_both_inStream_a_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_a_TDATA),
    .vld_in(inStream_a_TVALID),
    .ack_in(regslice_both_inStream_a_U_ack_in),
    .data_out(inStream_a_TDATA_int_regslice),
    .vld_out(inStream_a_TVALID_int_regslice),
    .ack_out(inStream_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream_a_U_apdone_blk)
);

yolo_acc_top_regslice_both #(
    .DataWidth( 112 ))
regslice_both_inStream_b_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(inStream_b_TDATA),
    .vld_in(inStream_b_TVALID),
    .ack_in(regslice_both_inStream_b_U_ack_in),
    .data_out(inStream_b_TDATA_int_regslice),
    .vld_out(inStream_b_TVALID_int_regslice),
    .ack_out(inStream_b_TREADY_int_regslice),
    .apdone_blk(regslice_both_inStream_b_U_apdone_blk)
);

yolo_acc_top_regslice_both #(
    .DataWidth( 112 ))
regslice_both_outStream_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TDATA),
    .vld_in(grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TVALID),
    .ack_in(outStream_TREADY_int_regslice),
    .data_out(outStream_TDATA),
    .vld_out(regslice_both_outStream_U_vld_out),
    .ack_out(outStream_TREADY),
    .apdone_blk(regslice_both_outStream_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_ready == 1'b1)) begin
            grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_ready == 1'b1)) begin
            grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        bias_en_read_reg_194 <= bias_en;
        fold_input_ch_read_reg_205 <= fold_input_ch;
        input_h_read_reg_219 <= input_h;
        input_w_read_reg_213 <= input_w;
        leaky_read_reg_200 <= leaky;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bound4_reg_250 <= grp_fu_187_p2;
        cmp_i_i31_mid111_reg_255 <= cmp_i_i31_mid111_fu_174_p2;
        icmp_ln1027_reg_260 <= icmp_ln1027_fu_181_p2;
        sub_i_i54_reg_240 <= sub_i_i54_fu_157_p2;
        sub_i_i_reg_245 <= sub_i_i_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bound_reg_225 <= bound_fu_141_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_outStream_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_outStream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_outStream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | ((grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_fu_187_ce = 1'b1;
    end else begin
        grp_fu_187_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        inStream_a_TREADY_int_regslice = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_inStream_a_TREADY;
    end else begin
        inStream_a_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        inStream_b_TREADY_int_regslice = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_inStream_b_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        inStream_b_TREADY_int_regslice = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_inStream_b_TREADY;
    end else begin
        inStream_b_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kernel_bias_fp_V_address0 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_bias_fp_V_address0 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_address0;
    end else begin
        kernel_bias_fp_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kernel_bias_fp_V_address1 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_bias_fp_V_address1 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_address1;
    end else begin
        kernel_bias_fp_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kernel_bias_fp_V_ce0 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_bias_fp_V_ce0 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_ce0;
    end else begin
        kernel_bias_fp_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kernel_bias_fp_V_ce1 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_kernel_bias_fp_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_bias_fp_V_ce1 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_ce1;
    end else begin
        kernel_bias_fp_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_bias_fp_V_we0 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_we0;
    end else begin
        kernel_bias_fp_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        kernel_bias_fp_V_we1 = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_kernel_bias_fp_V_we1;
    end else begin
        kernel_bias_fp_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((regslice_both_outStream_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bound_fu_141_p0 = bound_fu_141_p00;

assign bound_fu_141_p00 = input_w_read_reg_213;

assign bound_fu_141_p1 = bound_fu_141_p10;

assign bound_fu_141_p10 = fold_input_ch_read_reg_205;

assign cmp_i_i31_mid111_fu_174_p2 = ((sub_i_i54_fu_157_p2 == 10'd0) ? 1'b1 : 1'b0);

assign grp_fu_187_p0 = grp_fu_187_p00;

assign grp_fu_187_p00 = input_h_read_reg_219;

assign grp_fu_187_p1 = grp_fu_187_p10;

assign grp_fu_187_p10 = bound_fu_141_p2;

assign grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start = grp_yolo_acc_top_Pipeline_VITIS_LOOP_25_1_fu_106_ap_start_reg;

assign grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start = grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_ap_start_reg;

assign grp_yolo_acc_top_Pipeline_VITIS_LOOP_42_2_VITIS_LOOP_45_3_VITIS_LOOP_48_4_fu_115_outStream_TREADY = (outStream_TREADY_int_regslice & ap_CS_fsm_state6);

assign icmp_ln1027_fu_181_p2 = ((fold_input_ch_read_reg_205 == 4'd0) ? 1'b1 : 1'b0);

assign inStream_a_TREADY = regslice_both_inStream_a_U_ack_in;

assign inStream_b_TREADY = regslice_both_inStream_b_U_ack_in;

assign input_h_cast_fu_164_p1 = input_h_read_reg_219;

assign input_w_cast_fu_154_p1 = input_w_read_reg_213;

assign outStream_TVALID = regslice_both_outStream_U_vld_out;

assign sub_i_i54_fu_157_p2 = ($signed(input_w_cast_fu_154_p1) + $signed(10'd1023));

assign sub_i_i_fu_167_p2 = ($signed(input_h_cast_fu_164_p1) + $signed(10'd1023));


reg find_kernel_block = 0;
// synthesis translate_off
`include "yolo_acc_top_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //yolo_acc_top

