
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xyolo_upsamp_top.h"

/*
* The configuration table for devices
*/

XYolo_upsamp_top_Config XYolo_upsamp_top_ConfigTable[XPAR_XYOLO_UPSAMP_TOP_NUM_INSTANCES] =
{
	{
		XPAR_YOLO_UPSAMP_TOP_0_DEVICE_ID,
		XPAR_YOLO_UPSAMP_TOP_0_S_AXI_CTRL_BUS_BASEADDR
	}
};


